package org.sitenv.ccdaparsing.model;

public enum UsrhSubType {
	CONSULTATION_NOTE, CONTINUITY_OF_CARE_DOCUMENT, DIAGNOSTIC_IMAGING_REPORT, DISCHARGE_SUMMARY, 
	HISTORY_AND_PHYSICAL_NOTE, OPERATIVE_NOTE, PROCEDURE_NOTE, PROGRESS_NOTE, UNSTRUCTURED_DOCUMENT, 
	CARE_PLAN, REFERRAL_NOTE, TRANSFER_SUMMARY, US_REALM_HEADER_PATIENT_GENERATED_DOCUMENT
}
